name: User Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  stage-3-create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    steps:
      - name: Create User
        run: |
          # Script to create user
          # Assuming it's a placeholder

  manual-approval:
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    outputs:
      approved: ${{ steps.approve.outputs.approved }}
    steps:
      - name: Manual Approval
        id: approve
        run: echo "::set-output name=approved::true" # Change to false to simulate disapproval

  stage-4-reject:
    if: ${{ needs.manual-approval.outputs.approved == 'false' }}
    runs-on: ubuntu-latest
    steps:
      - name: Reject User
        run: |
          # Script to reject user
          # Assuming it's a placeholder

  stage-5-approve:
    if: ${{ needs.manual-approval.outputs.approved == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Approve User
        run: |
          # Script to approve user
          # Assuming it's a placeholder
