name: User Approval Workflow
on:
  push:
    branches:
      - master

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  stage-3-create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        approve-user: [false]
      fail-fast: false
    steps:
      - name: Create User
        id: create-user
        run: |
          echo "User creation logic here"
        continue-on-error: true

      - name: Set Approval Flag
        if: ${{ always() }}
        run: echo "::set-output name=approve-user::true"

  stage-4-approve:
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    if: ${{ needs.stage-3-create-user.outputs.approve-user == 'true' }}
    steps:
      - name: Approve User
        run: echo "User approved"

  stage-5-reject:
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    if: ${{ needs.stage-3-create-user.outputs.approve-user != 'true' }}
    steps:
      - name: Reject User
        run: echo "User rejected"
