name: Manual Approval Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building application..."

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run tests
        run: echo "Running tests..."

  deploy_to_staging:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  approve_staging:
    runs-on: self-hosted
    needs: deploy_to_staging
    if: github.event_name == 'pull_request'
    steps:
      - name: Request approval for Staging
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number
            });

            const reviewers = ["sarakishore", "ashoklogicfocus"]; // Add your reviewers
            const approvers = pullRequest.requested_reviewers.map(reviewer => reviewer.login);
            const needsApproval = reviewers.some(reviewer => !approvers.includes(reviewer));

            if (needsApproval) {
              await github.pulls.requestReviewers({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                reviewers: reviewers
              });
            }

  deploy_to_production:
    runs-on: self-hosted
    needs: [approve_staging, test]
    environment:
      name: production
      url: https://github.com/sarakishore
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."
