name: Manual Approval Pipeline

on:
  workflow_dispatch:  # Triggered manually

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build
        run: echo "Building application..."

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Run tests
        run: echo "Running tests..."

  deploy_to_staging:
    runs-on: self-hosted
    needs: test
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging..."

  approve_staging:
    runs-on: self-hosted
    needs: deploy_to_staging
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Manual approval for Staging
        run: echo "Please manually approve staging deployment."

  deploy_to_production:
    runs-on: self-hosted
    needs: [approve_staging, test]
    environment:
      name: production
      url: https://github.com/sarakishore
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production..."
