name: Build and User Approval Workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build Application
        run: |
          echo "Building Application"
          chmod -R 777 gradlew
          ./gradlew build
  create-user-and-approve:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create User
        run: echo "Creating User"
      - name: Await Approval
        id: approval
        run: echo "::set-output name=approved::true"
        continue-on-error: true
  deploy:
    runs-on: ubuntu-latest
    needs: create-user-and-approve
    if: ${{ needs.create-user-and-approve.outputs.approved == 'true' }}
    steps:
      - name: Deploy Application
        run: echo "Deploying Application"









