name: User Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  stage-3-create-user:
    needs: stage-2-echo
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.approval == 'true' }}
    steps:
      - name: Create User
        run: |
          #!/bin/bash

          # Define your GitHub username and token
          GITHUB_USERNAME="sarakishore"
          GITHUB_TOKEN="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"

          # Define the username you want to create
          NEW_USERNAME="Ashok"

          # Create the user using GitHub API
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/admin/users \
            -d "{\"login\":\"$NEW_USERNAME\"}"

          # Print success message
          echo "User $NEW_USERNAME created successfully."

  stage-4-reject:
    if: failure()
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    steps:
      - name: Reject User
        run: |
          # Script to reject user
          # Assuming it's a placeholder

  stage-5-approve:
    if: success()
    needs: stage-3-create-user
    runs-on: ubuntu-latest
    steps:
      - name: Approve User
        run: |
          # Script to approve user
          # Assuming it's a placeholder
