name: User Approval Workflow

on:
  push:
    branches:
      - main

jobs:
  stage-1-echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 1
        run: echo "Stage 1"

  stage-2-echo:
    needs: stage-1-echo
    runs-on: ubuntu-latest
    steps:
      - name: Echo Stage 2
        run: echo "Stage 2"

  stage-3-create-user:
    runs-on: ubuntu-latest
    needs: stage-2-echo
    steps:
      - name: Create User
        run: |
          # Script to create user
          # Assuming it's a placeholder

  manual-approval:
    runs-on: ubuntu-latest
    needs: stage-3-create-user
    outputs:
      approval_status: ${{ steps.approval.outputs.approval_status }}
    steps:
      - name: Manual Approval
        id: approval
        run: echo "Please approve or reject user creation."
      - name: Set Approval Output
        if: steps.approval.outputs.return-value == 'approve'
        run: echo "::set-output name=approval_status::approve"
      - name: Set Rejection Output
        if: steps.approval.outputs.return-value == 'reject'
        run: echo "::set-output name=approval_status::reject"

  stage-4-reject:
    if: ${{ needs.manual-approval.outputs.approval_status == 'reject' }}
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - name: Reject User
        run: |
          # Script to reject user
          # Assuming it's a placeholder

  stage-5-approve:
    if: ${{ needs.manual-approval.outputs.approval_status == 'approve' }}
    needs: manual-approval
    runs-on: ubuntu-latest
    steps:
      - name: Approve User
        run: |
          # Script to approve user
          # Assuming it's a placeholder
